name: CI/CD with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/test:${{ github.run_number }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_docker_image
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to server
        run: |
          echo "Deploying to server..."
          ssh -o StrictHostKeyChecking=no root@119.59.103.209
          "docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/test:${{ github.run_number }} && 
          docker stop test-web || true && docker rm test-web || true && 
          docker run -d --name test-web ${{ secrets.DOCKER_HUB_USERNAME }}/test:${{ github.run_number }}"